# Generated by Django 4.2.3 on 2024-01-23 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="last name"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=13, verbose_name="Contact phone number"
                    ),
                ),
                ("birth_date", models.DateField(null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("admin", "admin"), ("user", "user")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "login_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Google", "Google"),
                            ("Facebook", "Facebook"),
                            ("GitHub", "GitHub"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="vyoga_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="vyoga_user_permission",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_no",
                    models.CharField(blank=True, default="", max_length=12, null=True),
                ),
                (
                    "house_no",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "locality",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "lat",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "lng",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "landmark",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "district",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "pincode",
                    models.CharField(blank=True, default="", max_length=6, null=True),
                ),
                ("full_address", models.TextField(blank=True, default="", null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_address",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
