# Generated by Django 4.2.3 on 2024-01-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("age", models.IntegerField(default=0)),
                ("hotel_name", models.CharField(default="", max_length=30)),
                ("hotel_address", models.CharField(default="", max_length=30)),
                ("country", models.CharField(default="", max_length=30)),
                ("phone_number", models.CharField(default="", max_length=30)),
                ("url", models.CharField(default="", max_length=30)),
                ("description", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
